version: "3.8"

services:
  mysql:
    image: mysql
    restart: no
    env_file:
      - ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
  app:
    depends_on:
      - mysql
    restart: on-failure
    image: online-book-store-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
         "spring.datasource.url" : "jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DB",
         "spring.datasource.username" : "$MYSQL_USER",
         "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
         "spring.jpa.properties.hibernate.dialect" : "$MYSQL_DIALECT"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
